description = '''
Claude React Template
'''

[repo]
path = "/Users/arlan/prj/claude-react-template"

project_prompt = '''
- Be concise and dont spammy or noisy, we need to optimize tokens.
- Please always start with simple way and easy to understand result.
'''


[commands]
dev = ["next", "dev"]
build = ["next", "build"]
postbuild = ["cross-env", "NODE_OPTIONS=--loader ts-node/esm", "ts-node", "--project", "tsconfig.scripts.json", "scripts/generate-sitemap.ts"]
start = ["next", "start"]
lint = ["next", "lint"]