// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://awesome.supabase.co"; // Replace with your Supabase URL
const SUPABASE_PUBLISHABLE_KEY = "awesome_key"; // Replace with your Supabase publishable key

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
