// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://cfrothmeewkddunbkzjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmcm90aG1lZXdrZGR1bmJremp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MzgxNzYsImV4cCI6MjA2MDAxNDE3Nn0.WqTbyQF8BP0M2_SkD6PDAkpGhHjae-HevUniAE8I0Ro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
